config/routes.rb
Rails.application.routes.draw do
  root 'home#show'
  get 'home', to: 'home#show'

  get 'me', to: 'galleries#index', as: 'me'
  
  get '/galleries/apply_algorithm', to: 'galleries#apply_algorithm' 
  get '/galleries/apply_algorithm2', to: 'galleries#apply_algorithm2' 
  get '/galleries/apply_algorithm3', to: 'galleries#apply_algorithm3' 
  get '/galleries/manipulate', to: 'galleries#manipulate'

  resources :galleries do
    resources :file_uploads, only: [:new, :create, :destroy]
  end

  get 'users/whoami', to: 'user#whoami'
  get 'login', to: redirect('/auth/google_oauth2'), as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gallery.rb
class Gallery < ApplicationRecord
	validates :name, presence: true, allow_blank: false, uniqueness: { case_sensitive: false }

	has_many_attached :files
end

app/models/user.rb
class User < ApplicationRecord
    def self.find_or_create_from_auth_hash(auth)
		where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
			user.provider = auth.provider
			user.uid = auth.uid
			user.first_name = auth.info.first_name
			user.last_name = auth.info.last_name
			user.email = auth.info.email
			user.save!
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    helper_method :current_user
  
    def authenticate
        redirect_to :login unless user_signed_in?
    end
  
    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
  
    def user_signed_in?
        # converts current_user to a boolean by negating the negation
        !!current_user
    end
end

app/controllers/file_uploads_controller.rb
class FileUploadsController < ApplicationController
  def new
    @gallery = Gallery.find(params[:gallery_id])
  end

  def create
    @gallery = Gallery.find(params[:gallery_id])
    @gallery.files.attach(params[:gallery][:files])
    redirect_to gallery_path(@gallery)
  end

  def destroy
    @gallery = Gallery.find(params[:gallery_id])
    @gallery.files.find(params[:id]).purge
    redirect_to gallery_path(@gallery)
  end

end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :authenticate

  before_action :set_gallery, only: [:show, :edit, :update, :destroy]

  # GET /galleries
  # GET /galleries.json
  def index
    @galleries = Gallery.all
  end

  # GET /galleries/1
  # GET /galleries/1.json
  def show
  end

  # GET /galleries/new
  def new
    @gallery = Gallery.new
  end

  # GET /galleries/1/edit
  def edit
  end

  # POST /galleries
  # POST /galleries.json
  def create
    @gallery = Gallery.new(gallery_params)
    @gallery.owner = current_user.email

    respond_to do |format|
      if @gallery.save
        format.html { redirect_to @gallery, notice: 'Gallery was successfully created.' }
        format.json { render :show, status: :created, location: @gallery }
      else
        format.html { render :new }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /galleries/1
  # PATCH/PUT /galleries/1.json
  def update
    respond_to do |format|
      if @gallery.update(gallery_params)
        format.html { redirect_to @gallery, notice: 'Gallery was successfully updated.' }
        format.json { render :show, status: :ok, location: @gallery }
      else
        format.html { render :edit }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1
  # DELETE /galleries/1.json
  def destroy
    @gallery.destroy
    respond_to do |format|
      format.html { redirect_to galleries_url, notice: 'Gallery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def manipulate
    @img = params[:img]
    @gallery = Gallery.find(params[:gal])
  end

  def apply_algorithm
    @img = params[:img]
	@gallery = Gallery.find(params[:gal])
  end

  def apply_algorithm2
    @img = params[:img]
	@gallery = Gallery.find(params[:gal])
  end

  def apply_algorithm3
    @img = params[:img]
    @gallery = Gallery.find(params[:gal])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gallery
      @gallery = Gallery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gallery_params
      params.require(:gallery).permit(:name, :owner)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def show
    end
end

app/controllers/me_controller.rb
class MeController < ApplicationController
    before_action :authenticate
    def show
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def create
        @user = User.find_or_create_from_auth_hash(request.env["omniauth.auth"])
        session[:user_id] = @user.id
        redirect_to :me
    end
  
    def destroy
        session[:user_id] = nil
        redirect_to root_path
    end
  end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def whoami
    @user = User.find session[:user_id]
  end
end

app/views/file_uploads/new.html.haml
%link{:href => "https://fonts.googleapis.com/css?family=Montserrat&display=swap", :rel => "stylesheet"}/
%link{:href => "https://fonts.googleapis.com/css?family=Megrim&display=swap", :rel => "stylesheet"}/

.box_basic
  %h1
    Upload for Gallery 
    %br
    %br
    %br
    %br
    #{@gallery.name}
  %br
  %br
  %br
  %center
    = form_with model: @gallery, url: gallery_file_uploads_path(@gallery), :class => 'form_text', method: :post, local: true do |f|
      = f.file_field :files, multiple: true, direct_upload: true
      %br/
      %br/
      = f.submit 'Upload', :class => 'btn_basic btn_text', :id => 'file_upload_btn'
      %br
      %br
      %br
      %br
    = link_to 'Back', :back, :class => 'btn_basic btn_text', :id => 'new_gal_back_btn'

app/views/galleries/_form.html.haml
%link{:href => "https://fonts.googleapis.com/css?family=Montserrat&display=swap", :rel => "stylesheet"}/
%link{:href => "https://fonts.googleapis.com/css?family=Megrim&display=swap", :rel => "stylesheet"}/

= form_for @gallery do |f|
  %center
    - if @gallery.errors.any?
      #error_explanation
        %h2= "#{pluralize(@gallery.errors.count, "error")} prohibited this gallery from being saved:"
        %ul
          - @gallery.errors.full_messages.each do |message|
            %li
              = message 

    = f.label :name, :class => 'form_text', :id => 'form_label'
    = f.text_field :name
    %br
    %br
    = f.submit 'Save', :class => 'btn_basic btn_text', :id => 'new_gal_back_btn'

app/views/galleries/apply_algorithm.html.haml
%link{:href => "https://fonts.googleapis.com/css?family=Montserrat&display=swap", :rel => "stylesheet"}/
%link{:href => "https://fonts.googleapis.com/css?family=Megrim&display=swap", :rel => "stylesheet"}/

.box_basic.apply_algorithm
  %h1 Applying Algorithm 1
  %br
  %center
    = link_to 'Back', galleries_manipulate_path(:img => @img, :gal => @gallery), :class => 'btn_basic btn_text'
    %br
    %br

  = image_tag(@gallery.files.find(@img), :class => 'imgs')

  %center
    %script{src: "https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.8.0/p5.min.js"}
    
    %script{src: "../assets/algorithm1.js"} 

    %br

    = link_to 'Algorithm 2', galleries_apply_algorithm2_path(:img => @img, :gal => @gallery), :class => 'btn_basic btn_text', :id => 'alg2'

    = link_to 'Algorithm 3', galleries_apply_algorithm3_path(:img => @img, :gal => @gallery), :class => 'btn_basic btn_text', :id => 'alg3'

app/views/galleries/apply_algorithm2.html.haml
%link{:href => "https://fonts.googleapis.com/css?family=Montserrat&display=swap", :rel => "stylesheet"}/
%link{:href => "https://fonts.googleapis.com/css?family=Megrim&display=swap", :rel => "stylesheet"}/

.box_basic.apply_algorithm
  %h1 Applying Algorithm 2
  %br
  %center
    = link_to 'Back', galleries_manipulate_path(:img => @img, :gal => @gallery), :class => 'btn_basic btn_text'
    %br
    %br

  = image_tag(@gallery.files.find(@img), :class => 'imgs')

  %center
    %script{src: "https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.8.0/p5.min.js"}

    %script{src: "https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.8.0/addons/p5.dom.min.js"}

    %script{src: "../assets/algorithm2.js"} 

    %br

    = link_to 'Algorithm 1', galleries_apply_algorithm_path(:img => @img, :gal => @gallery), :class => 'btn_basic btn_text'

    = link_to 'Algorithm 3', galleries_apply_algorithm3_path(:img => @img, :gal => @gallery), :class => 'btn_basic btn_text'

app/views/galleries/apply_algorithm3.html.haml
%link{:href => "https://fonts.googleapis.com/css?family=Montserrat&display=swap", :rel => "stylesheet"}/
%link{:href => "https://fonts.googleapis.com/css?family=Megrim&display=swap", :rel => "stylesheet"}/

.box_basic.apply_algorithm
  %h1 Applying Algorithm 3
  %br
  %center
    = link_to 'Back', galleries_manipulate_path(:img => @img, :gal => @gallery), :class => 'btn_basic btn_text'
    %br
    %br

  = image_tag(@gallery.files.find(@img), :class => 'imgs')

  %center
    %script{src: "https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.8.0/p5.min.js"}

    %script{src: "https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.8.0/addons/p5.dom.min.js"}

    %script{src: "https://unpkg.com/p5.createloop@latest/dist/p5.createloop.js"}

    %script{src: "../assets/algorithm3.js"} 

    %br
    %br
    %br
    %br
    %br
    %br

    = link_to 'Algorithm 1', galleries_apply_algorithm_path(:img => @img, :gal => @gallery), :class => 'btn_basic btn_text'

    = link_to 'Algorithm 2', galleries_apply_algorithm2_path(:img => @img, :gal => @gallery), :class => 'btn_basic btn_text'

app/views/galleries/edit.html.haml
%link{:href => "https://fonts.googleapis.com/css?family=Montserrat&display=swap", :rel => "stylesheet"}/
%link{:href => "https://fonts.googleapis.com/css?family=Megrim&display=swap", :rel => "stylesheet"}/

.box_basic
	%h1 Editing gallery
	
	%br
	%br
	%br

	= render 'form'

	%br
	%br
	%br
	%br

	%center
		= link_to 'Back', galleries_path, :class => 'btn_basic btn_text', :id => 'new_gal_back_btn'

app/views/galleries/index.html.haml
%link{:href => "https://fonts.googleapis.com/css?family=Montserrat&display=swap", :rel => "stylesheet"}/
%link{:href => "https://fonts.googleapis.com/css?family=Megrim&display=swap", :rel => "stylesheet"}/

.box_basic
  %h1
    = current_user.first_name + "'s profile"  
  %br
  %br

  %center
    = link_to 'New Gallery', new_gallery_path, :class => 'btn_basic btn_text', :id => 'index_new_gal_btn'
  %br
  %br

  %h2 Listing galleries

  %center
    %table
      %tbody
        - galerias = Gallery.where(owner: current_user.email)
          - galerias.each do |gallery|
          %tr
            %td{:class => "index_txt"}
              %center
                = gallery.name
            
            %td
              = link_to "Show", gallery, {:class => 'btn_basic btn_text', :id => 'show'}
            
            %td
              = link_to "Edit", edit_gallery_path(gallery), {:class => 'btn_basic btn_text', :id => 'edit'}

            %td
              = link_to "Destroy", gallery, {:class => 'btn_basic btn_text', :id => 'destroy', method: :delete, data: { confirm: 'Do you really want to delete this gallery?'}}
  %br
  %br
  %br
  %br
  %br

  %center
    %a{href: "/", :class => 'btn_basic btn_text', :id => 'index_home_btn'} Home
    %a{href: "/logout", :class => 'btn_basic btn_text', :id => 'index_logout_btn'} Logout

app/views/galleries/manipulate.html.haml
%link{:href => "https://fonts.googleapis.com/css?family=Montserrat&display=swap", :rel => "stylesheet"}/
%link{:href => "https://fonts.googleapis.com/css?family=Megrim&display=swap", :rel => "stylesheet"}/

.box_basic
  %h1 Manipulation page
  %br
  %center
    = link_to 'Back', gallery_path(@gallery), :class => 'btn_basic btn_text'
    %br
    %br
    = image_tag(@gallery.files.find(@img), :class => 'imgs')

    %br
    %br
    =link_to 'Apply Algorithm 1', galleries_apply_algorithm_path(:img => @img, :gal => @gallery), :class => 'btn_basic btn_text', :id => 'alg1'

    =link_to 'Apply Algorithm 2', galleries_apply_algorithm2_path(:img => @img, :gal => @gallery), :class => 'btn_basic btn_text', :id => 'alg2'

    =link_to 'Apply Algorithm 3', galleries_apply_algorithm3_path(:img => @img, :gal => @gallery), :class => 'btn_basic btn_text', :id => 'alg3'

app/views/galleries/new.html.haml
%link{:href => "https://fonts.googleapis.com/css?family=Montserrat&display=swap", :rel => "stylesheet"}/
%link{:href => "https://fonts.googleapis.com/css?family=Megrim&display=swap", :rel => "stylesheet"}/

.box_basic
  %h1 New gallery
  
  %br
  %br
  %br

  = render 'form'

  %br
  %br
  %br
  %br

  %center
    = link_to 'Back', galleries_path, :class => 'btn_basic btn_text', :id => 'new_gal_back_btn'

app/views/galleries/show.html.haml
%link{:href => "https://fonts.googleapis.com/css?family=Montserrat&display=swap", :rel => "stylesheet"}/
%link{:href => "https://fonts.googleapis.com/css?family=Megrim&display=swap", :rel => "stylesheet"}/

.box_basic
  %center
    %h1
      = @gallery.name
      %br
      %br

    = link_to 'Edit', edit_gallery_path(@gallery),{ :class => 'btn_basic btn_text', :id => 'gal_edit'}
    
    = link_to 'Upload Files', new_gallery_file_upload_path(@gallery), {:class => 'btn_basic btn_text', :id => 'upload_file_btn'}

    = link_to 'Back', galleries_path,{:class => 'btn_basic btn_text', :id => 'show_back_btn'}
  
    %br

    %h2 Click on an image to manipulate it

    %ul
      - @gallery.files.each do |file|
        %dl
          = link_to image_tag(file, :class => 'imgs'), galleries_manipulate_path(:img => file, :gal => @gallery)
          
          %br

          = link_to "Delete image", gallery_file_upload_path(@gallery, file), :class => 'btn_basic btn_text', :id => 'show_del_image_btn', method: :delete, data: { confirm: "Do you really want to delete this image?"}
          %br
          %br
          %br

app/views/home/show.html.haml
%link{:href => "https://fonts.googleapis.com/css?family=Montserrat&display=swap", :rel => "stylesheet"}/
%link{:href => "https://fonts.googleapis.com/css?family=Megrim&display=swap", :rel => "stylesheet"}/

%body.background_gif

.box_basic
  %h1 RUPESTREE

  %h2
    %strong
      Edit your images applying generative algorithms
  - if not session[:user_id]
    %h2
      %a{:href => "/auth/google_oauth2", :class => 'btn_basic btn_text btn_home', :id => 'home_sign_in_btn'} Sign in with Google
  - else
    %h2
      %a{href: "/me", :class => 'btn_basic btn_text btn_home', :id => 'home_prof_btn'} Profile Page
      %br
      %br
      %a{href: "/logout", :class => 'btn_basic btn_text btn_home', :id => 'home_logout_btn'} Logout

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rupestree</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>